positive_fasta: example_input/deepmirgene/positive.fa
negative_fasta: example_input/deepmirgene/negative.fa
validation_positive_fasta: null
validation_negative_fasta: null
device: cuda
batch_size: 1
epochs: 1
validation_split: 0.2
seed: 1337
inference_input: data/smoke/tool_smoke_test.fa
