positive_fasta: exampke_input/mirdnn/positive.fa
negative_fasta: exampke_input/mirdnn/negative.fa
device: cpu
seq_length: 160
batch_size: 1
epochs: 1
early_stop: 1
valid_prop: 0.2
seed: 42
inference_input: benchmark/data/tool_smoke_test.fa
inference_batch_size: 1
