positiveIntervals: example_input/mustard/positive.bed
negativeIntervals: example_input/mustard/negative.bed
genome: example_input/mustard/genome.fa
consDir: example_input/mustard/consDir
classList: 1,2
classNum: 2
maxSize: 120
extFlag: 0
reinfNum: 1
shufClassFlag: 0
inputMode: sequence
modelType: CNN
threads: 1
excludedTestChroms: chrTest
excludedValidChroms: chrValid
chromList: all
winSize: 120
step: 5
staticPredFlag: 1
modelDirName: results
intermDir: results/mustard_intermediate
inference_input: example_input/mustard/positive.bed
