name: deepmirgene
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.5
  - biopython
  - scikit-learn=0.24.*
  - hdf5
  - make
  - perl
  - pkg-config
  - viennarna
  - cudatoolkit=11.2
  - cudnn=8.1
  - pip
  - pip:
      - tensorflow==2.6.0
      - keras==2.6.0
      - h5py
      - protobuf==3.20.*
