name: dnnpremir
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.20,<1.24
  - viennarna
  - pip
  - pip:
      - tensorflow==2.6.0
      - keras==2.6.0
      - h5py
      - protobuf==3.20.*
