name: mustard
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.20,<1.24
  - perl
  - perl-set-intervaltree
  - perl-parallel-forkmanager
  - perl-io-gzip
  - viennarna
  - bedtools
  - r-base
  - r-ggplot2
  - pip
  - pip:
      - tensorflow==2.6.0
      - keras==2.6.0
      - h5py
      - protobuf==3.20.*
