positive_fasta: example_input/deepmir/positive.fa
negative_fasta: example_input/deepmir/negative.fa
validation_positive_fasta: null
validation_negative_fasta: null
pretrain_positive_fasta: null
pretrain_negative_fasta: null
device: cuda
architecture: vgg
training_mode: base
modules: 1
dense_units: 32
filters: 8
batch_size: 1
epochs: 1
pretrain_epochs: 1
validation_split: 0.2
seed: 42
inference_input: benchmark/data/tool_smoke_test.fa
